{{- if .Values.grafana.sso.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-grafana-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.grafana.sso.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "app.fullname" . }}-grafana-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.grafana.sso.remoteKey | quote }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.grafana.sso.remoteKey | quote }}
        property: client_secret
{{- end }}
