{{- if and .Values.grafana.sso .Values.grafana.sso.enabled .Values.grafana.sso.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" . }}-grafana-aws-secrets
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: grafana
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: {{ include "app.fullname" . }}-grafana-aws-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.grafana.sso.externalSecret.key | quote }}
{{- end }}
