apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.name" . }}-{{ .Release.Name }}-configwatcher
spec:
  template:
    spec:
      containers:
        - name: {{ include "app.name" . }}-{{ .Release.Name }}-configwatcher
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache inotify-tools kubectl &&
              while inotifywait -m -e modify,create,delete --format '%w%f' {{ .Values.volumes.healthckecksioconfig.containerMountPath }} --include '\.ya?ml$'; do
                echo "File changed! Restarting pod...";
                kubectl delete pod -l app={{ include "app.name" . }}-{{ .Release.Name }};
              done
          volumeMounts:
        - name: {{ include "app.name" . }}-{{ .Release.Name }}-{{ .Values.volumes.healthckecksioconfig.name }}
          mountPath: {{ .Values.volumes.healthckecksioconfig.containerMountPath }}
      volumes:
      - name: {{ include "app.name" . }}-{{ .Release.Name }}-{{ .Values.volumes.healthckecksioconfig.name }}
        nfs:
          server: {{ .Values.volumes.healthckecksioconfig.server }}
          path: {{ .Values.volumes.healthckecksioconfig.path }}
      restartPolicy: Never
