{{- range .Values.redirects }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
spec:
  secretName: {{ .name }}-tls
  dnsNames:
{{- range .sources }}
    - {{ . }}
{{- end }}
  issuerRef:
    name: {{ .certIssuer | default "le-wildcard-issuer" }}
    kind: {{ .certIssuerKind | default "ClusterIssuer" }}
    group: {{ .certIssuerGroup | default "cert-manager.io" }}
{{- end }}