{{- range .Values.redirects }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}-tls
spec:
  secretName: {{ .name }}-tls
  dnsNames:
{{- range .sources }}
    - {{ . }}
{{- end }}
  issuerRef:
    name: {{ .cert-issuer | default "le-wildcard-issuer" }}
    kind: {{ .cert-issuer-kind | default "ClusterIssuer" }}
    group: {{ .cert-issuer-group | default "cert-manager.io" }}
{{- end }}