{{- if .Values.pods.ctbrec.ingress.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "app.name" . }}-ctbrecingressroute-tls
spec:
  secretName: {{ include "app.name" . }}-ctbrecingressroute-tls
  dnsNames:
    - {{ .Values.pods.ctbrec.ingress.host }}
  issuerRef:
    name: {{ index .Values.pods.ctbrec.ingress.annotations "cert-manager.io/cluster-issuer" }}
    kind: ClusterIssuer
{{- end }}

{{- if .Values.pods.ctbrec.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: no-tls-verify
spec:
  insecureSkipVerify: true
{{- end }}

{{- if .Values.pods.ctbrec.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "app.name" . }}-ctbrecingressroute
  annotations:
    {{- if .Values.pods.ctbrec.ingress.annotations }}
    {{- toYaml .Values.pods.ctbrec.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.pods.ctbrec.ingress.host }}`) 
      kind: Rule
      middlewares:
        - name: no-tls-verify
      services:
        - name: {{ include "app.name" . }}-ctbrechttpsservice
          port: {{ .Values.pods.ctbrec.httpsContainerPort }}
          scheme: https
          ServersTransport: no-tls-verify
  tls:
    secretName: {{ include "app.name" . }}-ctbrecingressroute-tls
{{- end }}