apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-ctbrechttpservice
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}-ctbrechttpservice
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # type: NodePort
  type: ClusterIP
  ports:
  - name: {{ include "app.name" . }}
    port: {{ .Values.pods.ctbrec.httpContainerPort }}
    targetPort: {{ .Values.pods.ctbrec.httpContainerPort }}
    # nodePort: {{ .Values.pods.ctbrec.httpExposedPort }}
  selector:
    app: {{ include "app.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-ctbrechttpsservice
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}-ctbrechttpsservice
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # type: NodePort
  type: ClusterIP
  ports:
  - name: {{ include "app.name" . }}
    port: {{ .Values.pods.ctbrec.httpsContainerPort }}
    targetPort: {{ .Values.pods.ctbrec.httpsContainerPort }}
    # nodePort: {{ .Values.pods.ctbrec.httpExposedPort }}
  selector:
    app: {{ include "app.name" . }}