apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiimages.name }}-pvc
  namespace: {{ template "app.name" . }}
spec:
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiimages.name }}-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.mediawikiimages.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiconfig.name }}-pvc
  namespace: {{ template "app.name" . }}
spec:
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiconfig.name }}-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.mediawikiconfig.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.mediawikidb.name }}-pvc
  namespace: {{ template "app.name" . }}
spec:
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.mediawikidb.name }}-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.mediawikidb.size }}
