apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiimages.name }}-volume
  namespace: {{ template "app.name" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.mediawikiimages.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiimages.name }}-volume
  mountOptions:
    - hard
    - intr
  nfs:
    path: {{ .Values.volumes.mediawikiimages.path }}
    server: {{ .Values.volumes.mediawikiimages.server }}
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiconfig.name }}-volume
#   namespace: {{ template "app.name" . }}
# spec:
#   capacity:
#     storage: {{ .Values.volumes.mediawikiconfig.size }}
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.mediawikiconfig.name }}-volume
#   mountOptions:
#     - hard
#     - intr
#   nfs:
#     path: {{ .Values.volumes.mediawikiconfig.path }}
#     server: {{ .Values.volumes.mediawikiconfig.server }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.mediawikidb.name }}-volume
  namespace: {{ template "app.name" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.mediawikidb.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.mediawikidb.name }}-volume
  mountOptions:
    - hard
    - intr
  nfs:
    path: {{ .Values.volumes.mediawikidb.path }}
    server: {{ .Values.volumes.mediawikidb.server }}
