apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "app.name" . }}
  name: {{ .Values.volumes.mediawikiconfig.name }}
type: Opaque
data:
  # LocalSettings.php: <base64-encoded-file-content>
  # {{ tpl (.Files.Glob "LocalSettings.php").AsSecrets . | indent 2 }}
  LocalSettings.php: {{ tpl (.Files.Get "LocalSettings.php") . | b64enc }}
