apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "app.name" . }}
  name: {{ .Values.volumes.mediawikiconfig.name }}
type: Opaque
data:
  # LocalSettings.php: <base64-encoded-file-content>
  {{ (.Files.Glob "LocalSettings.php").AsSecrets | indent 2 }}
