apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }} # has to match .spec.template.metadata.labels
  replicas: {{ .Values.pods.suwayomi.replicas }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }} # has to match .spec.selector.matchLabels
        # date: "{{ now | unixEpoch }}"
        app.kubernetes.io/name: {{ include "app.name" . }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      securityContext:
        runAsUser: {{ .Values.pods.suwayomi.security.runAsUser }}
        runAsGroup: {{ .Values.pods.suwayomi.security.runAsGroup }}
      {{- if .Values.pods.suwayomi.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.pods.suwayomi.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: suwayomi
        image: {{ .Values.pods.suwayomi.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pods.suwayomi.httpContainerPort }}
          name: suwayomi-http
        volumeMounts:
        - name: suwayomi-data
          mountPath: {{ .Values.volumes.suwayomidata.containerMountPath }}
        env:
          - name: TZ
            value: "Europe/Paris"
          {{- if .Values.pods.suwayomi.environment }}
            {{- toYaml .Values.pods.suwayomi.environment | nindent 10 }}
          {{- end }}

      - name: flaresolverr
        image: {{ .Values.pods.flaresolverr.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pods.flaresolverr.httpContainerPort }}
          name: flaresolverr
        env:
          - name: TZ
            value: "Europe/Paris"
          {{- if .Values.pods.flaresolverr.environment }}
            {{- toYaml .Values.pods.flaresolverr.environment | nindent 10 }}
          {{- end }}

      volumes:
      - name: suwayomi-data
        nfs:
          server: {{ .Values.volumes.suwayomidata.server }}
          path: {{ .Values.volumes.suwayomidata.path }}