teslamate:
  # nodeSelector:
  #   silent: fanless
  volumes:
    - name: import
      server: 192.168.2.50
      path: /volume2/docker-data/teslamate/import
      mountPath: /opt/app/import

  replicas: 1
  image: teslamate/teslamate:3.0
  pullPolicy: IfNotPresent
  nodeSelector:
    silent: fanless

  env:
    TZ: Europe/Paris
    ENCRYPTION_KEY: "randomsecretkey" # replace with a secure key to encrypt your Tesla API tokens
    DATABASE_USER: teslamate
    DATABASE_PASS: "password" # insert your secure database password
    DATABASE_NAME: teslamate
    DATABASE_PORT: 5432
    MQTT_HOST: mosquitto

  service:
    port: 4000

  ingress:
    enabled: true
    host: teslamate.arcanexus.com
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: le-wildcard-issuer
      traefik.ingress.kubernetes.io/router.middlewares: authentik-ak-outpost-authentik-embedded-outpost@kubernetescrd

database:
  image: postgres:18-trixie
  pullPolicy: IfNotPresent
  replicas: 1
  
  service:
    port: 5432
  
  shmSize: 128Mi

  env:
    TZ: Europe/Paris
    POSTGRES_USER: teslamate
    POSTGRES_PASSWORD: "password" # insert your secure database password
    POSTGRES_DB: teslamate

  volumes:
    database:
      server: 192.168.2.50
      path: /volume2/docker-data/teslamate/db
      containerMountPath: /var/lib/postgresql

grafana:
  image: teslamate/grafana:latest
  pullPolicy: IfNotPresent
  replicas: 1

  service:
    port: 3000
  
  nodeSelector:
    silent: fanless

  env:
    TZ: Europe/Paris
    GF_SERVER_ROOT_URL: "https://teslamate.arcanexus.com/grafana"
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    DATABASE_USER: teslamate
    DATABASE_PASS: "password" # insert your secure database password
    DATABASE_NAME: teslamate
    DATABASE_PORT: 5432
  
  sso:
    enabled: true
    env:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "CHANGEME_TESLAMATE_GRAFANA_CLIENT_ID"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "CHANGEME_TESLAMATE_GRAFANA_CLIENT_SECRET"
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email entitlements"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.arcanexus.com/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.arcanexus.com/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.arcanexus.com/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.arcanexus.com/application/o/teslamate-grafana/end-session/"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(entitlements[*], 'Grafana Admins') && 'Admin' || contains(entitlements[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_SIGN_UP: "true"

  volumes:
    - name: grafana
      server: 192.168.2.50
      path: /volume2/docker-data/teslamate/grafana
      containerMountPath: /var/lib/grafana

mosquitto:
  image: eclipse-mosquitto:2
  pullPolicy: IfNotPresent
  replicas: 1

  command: mosquitto -c /mosquitto-no-auth.conf

  service:
    port: 1883

  volumes:
    - name: mosquitto-conf
      server: 192.168.2.50
      path: /volume2/docker-data/teslamate/mosquitto/config
      containerMountPath: /mosquitto/config
    - name: mosquitto-data
      server: 192.168.2.50
      path: /volume2/docker-data/teslamate/mosquitto/data
      containerMountPath: /mosquitto/data
