apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ template "app.name" . }}
  name: {{ include "app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }} # has to match .spec.template.metadata.labels
  serviceName: {{ template "app.name" . }}-service
  replicas: {{ .Values.pods.piholeexporter.replicas }}
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }} # has to match .spec.selector.matchLabels
        date: "{{ now | unixEpoch }}"
    spec:
      terminationGracePeriodSeconds: 10
      # serviceAccountName: {{ include "app.name" . }}
      # automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.pods.piholeexporter.image }}
        ImagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.pods.piholeexporter.containerPort }}
          name: web
        env:
          - name: TZ
            value: "Europe/Paris"
          - name: PIHOLE_HOSTNAME
            value: "192.168.2.52"
          - name: PIHOLE_API_TOKEN
            value: ad911376f2867f7bb1ade8564291d4269fdd485a8b63af9e59672c219e51eeeb
          - name: PORT
            value: "9617"

