volumes:
  db:
    name: litellm-db
    server: 192.168.2.50
    path: /volume2/docker-data/litellm/db
    containerMountPath: /var/lib/postgresql/data


pods:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.63.14-stable
    replicas: 1

    httpContainerPort: 4000
    # httpsContainerPort: 8443
    # httpExposedPort: 30011

    # security:
    #   runAsUser: 0
    #   runAsGroup: 0

    ingress:
      enabled: true
      tls: true
      host: litellm.arcanexus.com
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer
    
    # nodeSelector:
    #   silent: fanless

    environment:
      - name: LITELLM_MASTER_KEY
        value: "sk-master-Sw4WaS4bkMMCNaYeTYa9"
      - name: STORE_MODEL_IN_DB
        value: "true"
  
  postgres:
    image: postgres:13.3
    replicas: 1

    database: litellm
    username: litellm
    password: litellm

ANTHROPIC_API_KEY: TBD