volumes:
  db:
    name: litellm-db
    server: 192.168.2.50
    path: /volume2/docker-data/litellm/db
    containerMountPath: /var/lib/postgresql/data

  openwebui:
    name: openwebui
    server: 192.168.2.50
    path: /volume2/docker-data/openwebui
    containerMountPath: /app/backend/data

pods:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.63.14-stable
    replicas: 1

    httpContainerPort: 4000
    # httpsContainerPort: 8443
    # httpExposedPort: 30011

    # security:
    #   runAsUser: 0
    #   runAsGroup: 0

    ingress:
      enabled: true
      tls: true
      host: litellm.arcanexus.com
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer
    
    # nodeSelector:
    #   silent: fanless

    litellm_master_key: "sk-master-Sw4WaS4bkMMCNaYeTYa9"

    environment:
      - name: STORE_MODEL_IN_DB
        value: "true"
  
  postgres:
    image: postgres:13.3
    replicas: 1

    database: litellm
    username: litellm
    password: litellm

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    replicas: 1

    httpContainerPort: 8080
    # httpsContainerPort: 8443
    # httpExposedPort: 30011

    # security:
    #   runAsUser: 0
    #   runAsGroup: 0

    ingress:
      enabled: true
      tls: true
      host: openwebui.arcanexus.com
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer
    
    # nodeSelector:
    #   silent: fanless

    environment:
      - name: WEBUI_AUTH
        value: "False"

ANTHROPIC_API_KEY: TBD
OPENAI_API_KEY: TBD