# volumes:
#   config:
#     name: litellm-config
#     server: 192.168.2.50
#     path: /volume2/docker/litellm/config
#     containerMountPath: /config


pods:
  litellm:
    image: ghcr.io/berriai/litellm:main-v1.63.14-stable
    replicas: 1

    httpContainerPort: 4000
    # httpsContainerPort: 8443
    # httpExposedPort: 30011

    # security:
    #   runAsUser: 0
    #   runAsGroup: 0

    ingress:
      enabled: true
      tls: true
      host: litellm.arcanexus.com
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer
    
    # nodeSelector:
    #   silent: fanless

ANTHROPIC_API_KEY: 