{{- if .Values.skooner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.skooner.serviceAccount.name }}
  namespace: {{ .Values.skooner.namespace }}
  labels:
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
