volumes:
  komgaconfig:
    name: komga-config
    path: /volume2/docker/komga/komga-config-k8s-nfs-pv
    server: 192.168.2.50
    containerMountPath: /config
  komgadata:
    name: komga-data
    path: /volume1/Data/ebook/BD
    server: 192.168.2.15
    containerMountPath: /nas_2_data
  komgadata2:
    name: komga-data2
    path: /volume2/docker/komga/komga-data-k8s-nfs-pv
    server: 192.168.2.50
    containerMountPath: /data

pods:
  komga:
    image: gotson/komga:latest
    replicas: 1
    httpContainerPort: 25600
    httpExposedPort: 30010

    ingress:
      enabled: true
      host: komga.arcanexus.com
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer