security:
  runAsUser: 0
  runAsGroup: 0

volumes:
  healthchecksioconfig:
    name: config
    server: 192.168.2.50
    path: /volume2/docker/monitoring-healthckecksio/config
    containerMountPath: /app/config/

pods:
  healthchecksio:
    image: ghcr.io/arcanexus/docker-healthchecksio:latest
    replicas: 1
    debug: "false"
    tz: "Europe/Paris"




