apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}-stashingress
annotations:
  {{- if .Values.pods.stash.ingress.annotations }}
  {{- toYaml .Values.pods.stash.ingress.annotations | nindent 2 }}
  {{- end }}
spec:
  ingressClassName: traefik
  {{- if .Values.pods.stash.ingress.enabled }}
  tls:
    - hosts:
        - {{ .Values.pods.stash.ingress.host }}
      secretName: {{ include "app.name" . }}-stashingress-tls
  {{- end }}
  rules:
    - host: {{ .Values.pods.stash.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "app.name" . }}-stashhttpservice
                port:
                  number: {{ .Values.pods.stash.httpContainerPort }}