apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.freshrssextensions.name }}-volume
  namespace: {{ template "app.name" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.freshrssextensions.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.freshrssextensions.name }}-volume
  mountOptions:
    - hard
    - intr
  nfs:
    path: {{ .Values.volumes.freshrssextensions.path }}
    server: {{ .Values.volumes.freshrssextensions.server }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.freshrssdata.name }}-volume
  namespace: {{ template "app.name" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.freshrssdata.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.freshrssdata.name }}-volume
  mountOptions:
    - hard
    - intr
  nfs:
    path: {{ .Values.volumes.freshrssdata.path }}
    server: {{ .Values.volumes.freshrssdata.server }}
