apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.freshrssextensions.name }}-pvc
  namespace: {{ template "app.name" . }}
spec:
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.freshrssextensions.name }}-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.freshrssextensions.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.freshrssdata.name }}-pvc
  namespace: {{ template "app.name" . }}
spec:
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.freshrssdata.name }}-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.freshrssdata.size }}
