apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-freshrsshttpservice
  namespace: {{ template "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}-freshrsshttpservice
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.pods.freshrss.httpContainerPort }}
    targetPort: {{ .Values.pods.freshrss.httpContainerPort }}
    name: {{ include "app.name" . }}
    nodePort: {{ .Values.pods.freshrss.httpExposedPort }}
  selector:
    app: {{ include "app.name" . }}
