# externalPostgreSQL:
#   enabled: true
#   image: postgres:17-alpine
#   host: postgres
#   port: 5432
#   username: authentik
#   password: ThisIsNotASecurePassword
#   database: authentik
  
#   nodeSelector:
#     silent: fanless

#   volume:
#     authentikData:
#       server: 192.168.2.50
#       path: /volume2/docker-data/authentik/postgresql
#       containerMountPath: /var/lib/postgresql/data/pgdata

volume:
  giteaDB:
    server: 192.168.2.50
    path: /volume2/docker-data/gitea/db
    storage: 10Gi
    claimName: gitea-db-pvc
  giteaData:
    server: 192.168.2.50
    path: /volume2/docker-data/gitea/data
    storage: 10Gi
    claimName: gitea-data-pvc

gitea:
  nodeSelector:
    silent: fanless

  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: le-wildcard-issuer
    hosts:
      - host: git.arcanexus.com
        paths:
          - path: /
    tls:
      - secretName: git-arcanexus-com-tls
        hosts:
          - git.arcanexus.com

  service:
    ssh:
      type: NodePort
      nodePort: 30222

  persistence:
    enabled: true
    create: false
    claimName: gitea-data-pvc

  postgresql:
    enabled: true
    primary:
      persistence:
        enabled: true
        existingClaim: gitea-db-pvc

  postgresql-ha:
    enabled: false

  valkey:
    enabled: false

  valkey-cluster:
    enabled: false

  gitea:
    admin:
      existingSecret:
      username: gitea_admin
      password: ChangeMe
      email: gitea@local.domain
      passwordMode: keepUpdated
    config:
      server:
        SSH_PORT: 22
        SSH_LISTEN_PORT: 2222

  arcrunner:
    enabled: true
    replicas: 1
    labels:
    - ubuntu-latest:docker://ghcr.io/arcanexus/gha-custom-runner:1.0.6

  deployment:
    env:
    - name: GITEA_RUNNER_REGISTRATION_TOKEN
      value: "TOKEN"