volumes:
  speedtesttrackerconfig:
    name: speedtest-tracker-config
    server: 192.168.2.50
    path: /volume2/docker/speedtest-tracker/config
    containerMountPath: /config


pods:
  speedtesttracker:
    image: henrywhitaker3/speedtest-tracker
    replicas: 1

    httpContainerPort: 80
    # httpsContainerPort: 8443
    # httpExposedPort: 30011

    environment:
      - name: OOKLA_EULA_GDPR
        value: "true"

    security:
      runAsUser: 911
      runAsGroup: 911

    ingress:
      enabled: true
      tls: true
      host: speedtest-tracker.arcanexus.com
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer
    
    # nodeSelector:
    #   silent: fanless

