{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-mariadb-root
type: Opaque
data:
  root-password: {{ .Values.mariadb.rootPassword | b64enc | quote }}
{{- end }}
---
{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-mariadb-user
type: Opaque
data:
  {{- if .Values.mariadb.user }}
  username: {{ .Values.mariadb.user | b64enc | quote }}
  password: {{ .Values.mariadb.password | b64enc | quote }}
  {{- end }}
{{- end }}
