externalPostgreSQL:
  enabled: true
  image: postgres:17-alpine
  host: postgres
  port: 5432
  username: authentik
  password: ThisIsNotASecurePassword
  database: authentik
  
  nodeSelector:
    silent: fanless

  volume:
    authentikData:
      server: 192.168.2.50
      path: /volume2/docker-data/authentik/postgresql
      containerMountPath: /var/lib/postgresql/data/pgdata

blueprintsInline: {}

blueprintsWatcher:
  enabled: true
  schedule: "*/1 * * * *"
  image: alpine/k8s:1.31.4
  imagePullPolicy: IfNotPresent
  secretName: authentik-blueprints
  stateConfigMapName: authentik-blueprints-watcher-state
  deploymentSelector: app.kubernetes.io/instance={{ .Release.Name }},app.kubernetes.io/name=authentik
  componentLabelKey: app.kubernetes.io/component
  components:
    - server
    - worker
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2

authentik:
  authentik:
    secret_key: PleaseGenerateASecureKey
    error_reporting:
      enabled: true
    postgresql:
      password: ThisIsNotASecurePassword

  global:
    nodeSelector:
      silent: fanless
    env:
      - name: AUTHENTIK_POSTGRESQL__HOST
        value: postgres
      - name: AUTHENTIK_POSTGRESQL__PORT
        value: "5432"
      - name: AUTHENTIK_POSTGRESQL__USER
        value: authentik
      - name: AUTHENTIK_POSTGRESQL__PASSWORD
        value: ThisIsNotASecurePassword
      - name: AUTHENTIK_POSTGRESQL__NAME
        value: authentik

  server:
    podAnnotations: {}
    startupProbe:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 360
    ingress:
      ingressClassName: traefik
      enabled: true
      https: false
      annotations:
        cert-manager.io/cluster-issuer: le-wildcard-issuer
      hosts:
        - authentik.arcanexus.com
      tls:
        - secretName: authentik-arcanexus-com-tls
          hosts:
            - authentik.arcanexus.com

  blueprints:
    secrets: []

  worker:
    podAnnotations: {}
    startupProbe:
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 360
    env:
      - name: AUTHENTIK_BOOTSTRAP_PASSWORD
        value: PleaseGenerateASecureBootstrapPassword
      - name: AUTHENTIK_BOOTSTRAP_EMAIL
        value: admin@arcanexus.com
  postgresql:
    enabled: false
    auth:
      password: ThisIsNotASecurePassword

