volumes:
  config:
    name: config
    containerMountPath: /app/config
    server: 192.168.2.50
    path: /volume2/docker/homepage/homepage-config-k8s-nfs-pv
  images:
    name: images
    containerMountPath: /app/public/images
    server: 192.168.2.50
    path: /volume2/docker/homepage/images
pods:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    replicas: 1
    containerPort: 3000
    exposedPort: 30001
    allowedHosts: "*"