apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-technitiumdns
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  {{- range .Values.technitiumdns.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: technitiumdns
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-technitiumdns-dns-udp
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  {{- range .Values.technitiumdns.service.ports }}
  {{- if eq .name "dns-udp" }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: technitiumdns
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-technitiumdns-web
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  {{- range .Values.technitiumdns.service.ports }}
  {{- if or (eq .name "web-http") (eq .name "web-https") }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: technitiumdns
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-technitiumdns-dns-tcp
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  {{- range .Values.technitiumdns.service.ports }}
  {{- if eq .name "dns-tcp" }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    nodePort: {{ .nodePort }}
    protocol: {{ .protocol | default "TCP" }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: technitiumdns
