apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.name" . }}-{{ .Release.Name }}-prometheus-config
data:
  {{- $files := .Values.prometheus.configFiles | default dict -}}
  {{- range $filename := keys $files | sortAlpha }}
  {{ $filename }}: |
{{ tpl (index $files $filename) $ | nindent 4 }}
  {{- end }}
