{{- if .Values.grafana.oauth.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" . }}-{{ .Release.Name }}-grafana-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.grafana.oauth.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "app.name" . }}-{{ .Release.Name }}-grafana-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.grafana.oauth.remoteKey | quote }}
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.grafana.oauth.remoteKey | quote }}
        property: client_secret
{{- end }}
