{{- if .Values.grafana.oauth.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-aws-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.grafana.oauth.secretStore }}
    kind: ClusterSecretStore
  target:
    name: grafana-aws-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.grafana.oauth.remoteKey | quote }}
{{- end }}
