{{- if .Values.grafana.sso.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "app.name" . }}-{{ .Release.Name }}-grafana-aws-secrets
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}-{{ .Release.Name }}-grafana
    helm.sh/chart: {{ include "app.chart" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: {{ include "app.name" . }}-{{ .Release.Name }}-grafana-aws-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.grafana.sso.externalSecret.key | quote }}
{{- end }}
