---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-aws-secrets" (include "tailscale-router.fullname" .) | quote }}
  labels:
    app.kubernetes.io/name: {{ include "tailscale-router.fullname" . | quote }}
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: {{ printf "%s-aws-secrets" (include "tailscale-router.fullname" .) | quote }}
    creationPolicy: Owner
  data:
    - secretKey: tailscale_client_id
      remoteRef:
        key: tailscale_client_id
    - secretKey: tailscale_client_secret
      remoteRef:
        key: tailscale_client_secret

