apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "app.name" . }}
  name: {{ include "app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "app.name" . }} # has to match .spec.template.metadata.labels
  replicas: {{ .Values.pods.snmpexporter.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }} # has to match .spec.selector.matchLabels
        date: "{{ now | unixEpoch }}"
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.pods.snmpexporter.image }}
        imagePullPolicy: Always
        args: ["--config.file=/etc/snmp_exporter/snmp.yml"]
        ports:
        - containerPort: {{ .Values.pods.snmpexporter.containerPort }}
          name: web
        volumeMounts:
        - name: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}
          mountPath: {{ .Values.volumes.config.containerMountPath }}
        env:
          - name: TZ
            value: "Europe/Paris"
      volumes:
      - name: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}
        persistentVolumeClaim:
          claimName: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}-pvc

