apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.config.name }}-pvc
  namespace: {{ template "app.name" . }}
spec:
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.config.name }}-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.config.size }}
