---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-aws-secrets
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" . | quote }}
    helm.sh/chart: {{ include "app.chart" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: grafana-aws-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "/authentik/grafana"

