apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  replicas: {{ .Values.pods.lokiexporter.replicas }}
  revisionHistoryLimit: 0
  #minReadySeconds: 10
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
        date: "{{ now | unixEpoch }}"
    spec:
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: {{ include "app.name" . }}
          image: {{ .Values.pods.lokiexporter.image }}
          imagePullPolicy: Always
          args: ["--config.file=/config/config.yaml"]
          ports:
            - containerPort: {{ .Values.pods.lokiexporter.containerPort }}
              name: web
          volumeMounts:
            - name: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}
              mountPath: {{ .Values.volumes.config.containerMountPath }}
          env:
            - name: TZ
              value: "Europe/Paris"
      volumes:
      - name: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}
        nfs:
          server: {{ .Values.volumes.config.server }}
          path: {{ .Values.volumes.config.path }}

