---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-aws-secrets" (include "app.fullname" .) | quote }}
  labels:
    app.kubernetes.io/name: {{ include "app.fullname" . | quote }}
    helm.sh/chart: {{ include "app.chart" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: {{ printf "%s-aws-secrets" (include "app.fullname" .) | quote }}
    creationPolicy: Owner
    template:
      data:
        username: {{ .Values.gitea.admin.username | quote }}
        password: '{{ "{{ .password }}" }}'
  data:
    - secretKey: password
      remoteRef:
        key: default_password

