apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-bentopdf
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}-bentopdf
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: {{ .Values.bentopdf.port }}
    targetPort: {{ .Values.bentopdf.port }}
  selector:
    app: {{ include "app.name" . }}-bentopdf
