apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
secrets:
  - name: {{ template "app.name" . }}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ template "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "app.name" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "app.name" . }}