apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
spec:
  replicas: {{ .Values.pods.homepage.replicas }}
  #minReadySeconds: 10
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
        app.kubernetes.io/name: {{ include "app.name" . }}
        helm.sh/chart: {{ include "app.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      # terminationGracePeriodSeconds: 10
      serviceAccountName: {{ include "app.name" . }}
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: {{ include "app.name" . }}
          image: {{ .Values.pods.homepage.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.pods.homepage.containerPort }}
              name: web
          volumeMounts:
            - name: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}
              mountPath: {{ .Values.volumes.config.containerMountPath }}
            - name: {{ include "app.name" . }}-{{ .Values.volumes.images.name }}
              mountPath: {{ .Values.volumes.images.containerMountPath }}
          env:
          - name: TZ
            value: "Europe/Paris"
          {{- if .Values.pods.homepage.environment }}
            {{- toYaml .Values.pods.homepage.environment | nindent 10 }}
          {{- end }}
      volumes:
      - name: {{ include "app.name" . }}-{{ .Values.volumes.config.name }}
        nfs:
          server: {{ .Values.volumes.config.server }}
          path: {{ .Values.volumes.config.path }}
      - name: {{ include "app.name" . }}-{{ .Values.volumes.images.name }}
        nfs:
          server: {{ .Values.volumes.images.server }}
          path: {{ .Values.volumes.images.path }}