apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: litellm-secrets
data:
  ANTHROPIC_API_KEY: {{ .Values.ANTHROPIC_API_KEY | b64enc }}

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: litellm-postgres-secrets
data:
  password: {{ .Values.pods.postgres.password | b64enc }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@litellm-postgres:5432/%s" .Values.pods.postgres.username .Values.pods.postgres.password .Values.pods.postgres.database | b64enc }}