apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.komgaconfig.name }}-volume
  namespace: {{ template "app.name" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.komgaconfig.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.komgaconfig.name }}-volume
  mountOptions:
    - hard
    - intr
  nfs:
    path: {{ .Values.volumes.komgaconfig.path }}
    server: {{ .Values.volumes.komgaconfig.server }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "app.name" . }}-{{ .Values.volumes.komgadata2.name }}-volume
  namespace: {{ template "app.name" . }}
spec:
  capacity:
    storage: {{ .Values.volumes.komgadata2.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "app.name" . }}-{{ .Values.volumes.komgadata2.name }}-volume
  mountOptions:
    - hard
    - intr
  nfs:
    path: {{ .Values.volumes.komgadata2.path }}
    server: {{ .Values.volumes.komgadata2.server }}
